apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-get-task-api
  template:
    metadata:
      labels:
        app: todo-get-task-api
    spec:
      containers:
      - name: todo-get-task-api
        image: zincovit.azurecr.io/todo-get-tasks-api:v1
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-server-todo.database.windows.net,1433;Database=tododb;Uid=azureuser;Pwd=Abhilash@7878;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

